#!/usr/bin/env python3
"""
Generate oui_list.h and vendor_list.h from signatures.py.

Run from the repo root:
    uv run esp32/gen_oui_header.py

Outputs:
  esp32/oui_list.h   — Flock detection tables
  esp32/vendor_list.h — US-market vendor OUI + BLE company-ID labels
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from flockdar import signatures as sig

OUI_OUTPUT = Path(__file__).parent / "oui_list.h"
VENDOR_OUTPUT = Path(__file__).parent / "vendor_list.h"

OUI_HEADER = """\
// oui_list.h — AUTO-GENERATED by esp32/gen_oui_header.py
// DO NOT EDIT. Run `uv run esp32/gen_oui_header.py` to regenerate.
// Source: signatures.py FLOCK_DIRECT_OUIS | FLOCK_CHIP_OUIS,
//         FLOCK_MFGRIDS, BLE_NAME_PATTERNS

#pragma once
#include <stddef.h>
#include <stdint.h>

"""

VENDOR_HEADER = """\
// vendor_list.h — AUTO-GENERATED by esp32/gen_oui_header.py
// DO NOT EDIT. Run `uv run esp32/gen_oui_header.py` to regenerate.
// Source: signatures.py VENDOR_OUIS (+ SURVEILLANCE_OUIS fallback)

#pragma once
#include <stddef.h>
#include <stdint.h>

struct VendorOui {
  uint8_t b0, b1, b2;
  const char *name;
};

struct BleVendor {
  uint16_t cid;
  const char *name;
};

"""


def _oui_to_bytes(oui: str) -> tuple[int, int, int]:
    parts = oui.split(":")
    return int(parts[0], 16), int(parts[1], 16), int(parts[2], 16)


def _merged_vendor_ouis() -> dict[str, str]:
    merged = dict(sig.SURVEILLANCE_OUIS)
    merged.update(sig.VENDOR_OUIS)
    return merged


def write_oui_list() -> int:
    all_ouis = sorted(sig.FLOCK_DIRECT_OUIS | sig.FLOCK_CHIP_OUIS)
    rows = []
    for oui in all_ouis:
        a, b, c = _oui_to_bytes(oui)
        rows.append(f"    {{0x{a:02X}, 0x{b:02X}, 0x{c:02X}}},  // {oui}")

    lines = [
        OUI_HEADER,
        f"static const uint8_t FLOCK_OUIS[][3] = {{\n",
        "\n".join(rows),
        f"\n}};\n",
        f"static const size_t FLOCK_OUI_COUNT = {len(all_ouis)};\n",
        "\n",
        "// BLE manufacturer IDs (decimal)\n",
        f"static const uint16_t FLOCK_MFGRIDS[] = {{",
        ", ".join(str(m) for m in sorted(sig.FLOCK_MFGRIDS)),
        f"}};\n",
        f"static const size_t FLOCK_MFGRID_COUNT = {len(sig.FLOCK_MFGRIDS)};\n",
        "\n",
        "// BLE advertisement name substrings (lowercase) — match case-insensitively\n",
        "// against the advertised device name. Source: signatures.BLE_NAME_PATTERNS\n",
        f"static const char *const FLOCK_BLE_NAMES[] = {{",
        ", ".join(f'"{p.lower()}"' for p in sig.BLE_NAME_PATTERNS),
        f"}};\n",
        f"static const size_t FLOCK_BLE_NAME_COUNT = {len(sig.BLE_NAME_PATTERNS)};\n",
    ]

    OUI_OUTPUT.write_text("".join(lines), encoding="utf-8")
    return len(all_ouis)


def write_vendor_list() -> tuple[int, int]:
    vendors = _merged_vendor_ouis()
    rows = []
    for oui in sorted(vendors):
        a, b, c = _oui_to_bytes(oui)
        name = vendors[oui].replace('"', '\\"')
        rows.append(f'    {{0x{a:02X}, 0x{b:02X}, 0x{c:02X}, "{name}"}},  // {oui}')

    ble_rows = []
    for cid in sorted(sig.BLE_VENDOR_IDS):
        name = sig.BLE_VENDOR_IDS[cid].replace('"', '\\"')
        ble_rows.append(f'    {{{cid}, "{name}"}},')

    lines = [
        VENDOR_HEADER,
        f"static const VendorOui VENDOR_OUIS[] = {{\n",
        "\n".join(rows),
        f"\n}};\n",
        f"static const size_t VENDOR_OUI_COUNT = {len(rows)};\n",
        "\n",
        f"static const BleVendor BLE_VENDORS[] = {{\n",
        "\n".join(ble_rows),
        f"\n}};\n",
        f"static const size_t BLE_VENDOR_COUNT = {len(ble_rows)};\n",
    ]

    VENDOR_OUTPUT.write_text("".join(lines), encoding="utf-8")
    return len(rows), len(ble_rows)


def main() -> None:
    flock_n = write_oui_list()
    oui_n, ble_n = write_vendor_list()
    print(
        f"Written {flock_n} Flock OUIs -> {OUI_OUTPUT.name}; "
        f"{oui_n} vendor OUIs, {ble_n} BLE vendor IDs -> {VENDOR_OUTPUT.name}"
    )


if __name__ == "__main__":
    main()
