#!/usr/bin/env python3
"""
Generate oui_list.h from the canonical signatures.py OUI sets.

Run from the repo root:
    uv run esp32/gen_oui_header.py

Outputs esp32/oui_list.h — include in the Arduino/PlatformIO sketch.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
import signatures as sig

OUTPUT = Path(__file__).parent / "oui_list.h"

HEADER = """\
// oui_list.h — AUTO-GENERATED by esp32/gen_oui_header.py
// DO NOT EDIT. Run `uv run esp32/gen_oui_header.py` to regenerate.
// Source: signatures.py FLOCK_DIRECT_OUIS | FLOCK_CHIP_OUIS

#pragma once
#include <stdint.h>

"""


def _oui_to_bytes(oui: str) -> tuple[int, int, int]:
    parts = oui.split(":")
    return int(parts[0], 16), int(parts[1], 16), int(parts[2], 16)


def main() -> None:
    all_ouis = sorted(sig.FLOCK_DIRECT_OUIS | sig.FLOCK_CHIP_OUIS)
    rows = []
    for oui in all_ouis:
        a, b, c = _oui_to_bytes(oui)
        rows.append(f"    {{0x{a:02X}, 0x{b:02X}, 0x{c:02X}}},  // {oui}")

    lines = [
        HEADER,
        f"static const uint8_t FLOCK_OUIS[][3] = {{\n",
        "\n".join(rows),
        f"\n}};\n",
        f"static const size_t FLOCK_OUI_COUNT = {len(all_ouis)};\n",
        "\n",
        "// BLE manufacturer IDs (decimal)\n",
        f"static const uint16_t FLOCK_MFGRIDS[] = {{",
        ", ".join(str(m) for m in sorted(sig.FLOCK_MFGRIDS)),
        f"}};\n",
        f"static const size_t FLOCK_MFGRID_COUNT = {len(sig.FLOCK_MFGRIDS)};\n",
    ]

    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"Written {len(all_ouis)} OUIs and {len(sig.FLOCK_MFGRIDS)} mfgrid(s) -> {OUTPUT}")


if __name__ == "__main__":
    main()
