// pins.h — AUTO-GENERATED by esp32/pin_spec.py. DO NOT EDIT.
// Regenerate:  uv run esp32/pin_spec.py gen   (run `validate` first)
//
// Board-conditional, validated GPIO assignments. See esp32/HARDWARE.md
// for the full pin specification, rationale, and wiring.
#pragma once

#if defined(CONFIG_IDF_TARGET_ESP32S3)  // ESP32-S3 (esp32-s3-devkitc-1)
#define FD_OLED_SDA 8  // I2C data  (SSD1306 OLED)
#define FD_OLED_SCL 9  // I2C clock (SSD1306 OLED)
#define FD_SD_CS 10  // SPI chip-select (microSD)
#define FD_SD_SCK 12  // SPI clock       (microSD)
#define FD_SD_MISO 13  // SPI MISO  (microSD -> ESP)
#define FD_SD_MOSI 11  // SPI MOSI  (ESP -> microSD)
#define FD_GPS_RX_PIN 18  // UART RX   (GPS TX -> ESP)
#define FD_GPS_TX_PIN 17  // UART TX   (ESP -> GPS RX)
#define FD_GPS_UART 1

#elif defined(CONFIG_IDF_TARGET_ESP32)  // ESP32 (esp32dev)
#define FD_OLED_SDA 21  // I2C data  (SSD1306 OLED)
#define FD_OLED_SCL 22  // I2C clock (SSD1306 OLED)
#define FD_SD_CS 5  // SPI chip-select (microSD)
#define FD_SD_SCK 18  // SPI clock       (microSD)
#define FD_SD_MISO 19  // SPI MISO  (microSD -> ESP)
#define FD_SD_MOSI 23  // SPI MOSI  (ESP -> microSD)
#define FD_GPS_RX_PIN 16  // UART RX   (GPS TX -> ESP)
#define FD_GPS_TX_PIN 17  // UART TX   (ESP -> GPS RX)
#define FD_GPS_UART 2

#else
#error "flockdar-esp32: no validated pin map for this target — add one in esp32/pin_spec.py and run `pin_spec.py gen`."
#endif
